title: Antique Aether
baseurl: "/antique-aether-2"
url: "https://deveyus.github.io"
markdown: kramdown
permalink: pretty

collections:
  worlds:
    output: true
    permalink: /worlds/:path/

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default
